const products = [
    {
        id: "1",
        category: "web-design",
        name: "Express",
        summary: "A multi-carrier shipping website for ecommerce businesses",
        img: "/web-design/desktop/image-express.jpg",
    },
    {
        id: "2",
        category: "web-design",
        name: "Transfer",
        summary: "Site for low-cost money transfers and sending money within seconds",
        img: "/web-design/desktop/image-transfer.jpg",
    },
    {
        id: "3",
        category: "web-design",
        name: "Photon",
        summary: "A state-of-the-art music player with high-resolution audio and DSP effects",
        img: "/web-design/desktop/image-photon.jpg",
    },
    {
        id: "4",
        category: "web-design",
        name: "Builder",
        summary: "Connects users with local contractors based on their location",
        img: "/web-design/desktop/image-builder.jpg",
    }, 
    {
        id: "5",
        category: "web-design",
        name: "Blogr",
        summary: "Blogr is a platform for creating an online blog or publication",
        img: "/web-design/desktop/image-blogr.jpg",
    }, 
    {
        id: "6",
        category: "web-design",
        name: "Camp",
        summary: "Get expert training in coding, data, design, and digital marketing",
        img: "/web-design/desktop/image-camp.jpg",
    }, 
    {
        id: "7",
        category: "app-design",
        name: "Airfilter",
        summary: "Solving the problem of poor indoor air quality by filtering the air",
        img: "/app-design/desktop/image-airfilter.jpg",
    },
    {
        id: "8",
        category: "app-design",
        name: "Eyecam",
        summary: "Product that lets you edit your favorite photos and videos at any time",
        img: "/app-design/desktop/image-eyecam.jpg",
    },
    {
        id: "9",
        category: "app-design",
        name: "Faceit",
        summary: "Get to meet your favorite internet superstar with the faceit app",
        img: "/app-design/desktop/image-faceit.jpg",
    },
    {
        id: "10",
        category: "app-design",
        name: "todo",
        summary: "A todo app that features cloud sync with light and dark mode",
        img: "/app-design/desktop/image-todo.jpg",
    }, 
    {
        id: "11",
        category: "app-design",
        name: "Loopstudios",
        summary: "A VR experience app made for Loopstudios",
        img: "/app-design/desktop/image-loopstudios.jpg",
    }, 
    {
        id: "12",
        category: "graphic-design",
        name: "Tim Brown",
        summary: "A book cover designed for Tim Brown’s new release, ‘Change’",
        img: "/graphic-design/desktop/image-change.jpg",
    },
    {
        id: "13",
        category: "graphic-design",
        name: "Boxed Water",
        summary: "A simple packaging concept made for Boxed Water",
        img: "/graphic-design/desktop/image-boxed-water.jpg",
    }, 
    {
        id: "14",
        category: "graphic-design",
        name: "Science!",
        summary: "A poster made in collaboration with the Federal Art Project",
        img: "/graphic-design/desktop/image-science.jpg",
    }, 
]

export default products